### PR TITLE
[DATACMNS-764][FIX] wrong implementation selected when same named repositories exist

### PR DESCRIPTION
**Pull request by xhaggi**
This solves the issue described in DATACMNS-764 by using the bean name of the repository interface instead of the simple class name to build the repository custom implementation bean name.

Example:
```
@Repository
public interface CarRepository {} -> Bean name: carRepository
public class CarRepositoryImpl {} -> Bean name: carRepositoryImpl
```

```
@Repository("myCarRepository")
public interface CarRepository {} -> Bean name: myCarRepository
public interface CarRepositoryImpl {} -> Bean name: myCarRepositoryImpl
```

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACMNS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@xhaggi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=193)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=193) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@xhaggi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=193)!

**Comment by schauder** [comment]
This PR gets replaced by https://github.com/spring-projects/spring-data-commons/pull/201

**Comment by xhaggi** [comment]
@schauder good to see some progress here. Thanks.

**Pull request closed without merging**
