### PR TITLE
DATACMNS-1454  Support multiple sorting fields in different directions in one sort parameter

### PR DESCRIPTION
**Pull request by andyslin**
Add support for multiple fields and sorting in different directions, while supporting direct use of database fields. If the last string is asc|desc, it is the default sort direction:
1. `field1_name desc, field2_name asc, field3Name desc` ==>`field1Name desc, field2Name asc, field3Name desc`
1. `field1_name, field2_name, desc` ==>`field1Name desc, field2Name desc`
1. `field1_name, field2_name asc, field3Name, desc` ==>`field1Name desc, field2Name asc, field3Name desc`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andyslin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=327)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=327) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by odrotbohm** [comment]
Please make sure you read and follow the contribution guidelines as asked for in the PR template. Otherwise it's unlikely that a PR is even processed. Thanks!

**Comment by odrotbohm** [comment]
Thanks for the update. Please make sure, you refer to a ticket discussing what you want to change (why is this better than the already existing format), why you want to change that and consequences for existing clients. We're not eager to change the format easily.

As far as I can see what you're trying to achieve is already possible by passing muliple sort parameters, i.e. `sort=foo,bar,asc&sort=fooBar,desc` already results in `foo asc, bar asc, fooBar, desc`.

**Comment by andyslin** [comment]
> Thanks for the update. Please make sure, you refer to a ticket discussing what you want to change (why is this better than the already existing format), why you want to change that and consequences for existing clients. We're not eager to change the format easily.
> 
> As far as I can see what you're trying to achieve is already possible by passing muliple sort parameters, i.e. `sort=foo,bar,asc&sort=fooBar,desc` already results in `foo asc, bar asc, fooBar, desc`.

Thank you for your reply, I am very sorry, I have not got the ticket for discussion.
But I want to do this for several reasons:
1. First of all, can be compatible with the original format 
2. Second, sometimes the page does not allow multiple sort parameters to be passed in, because this means that the dom structure needs to be dynamically added. 
3. Third, the new format (field name and sort syntax) is more in line with the habit of SQL. 

In addition, `foo,bar desc,fooBar` are not equivalent to `sort=foo,fooBar&sort=bar,desc`, but are equivalent to `sort=foot&sort=bar,desc&sort=footBar`, and easily confused

**Comment by andyslin** [comment]
> Thanks for the update. Please make sure, you refer to a ticket discussing what you want to change (why is this better than the already existing format), why you want to change that and consequences for existing clients. We're not eager to change the format easily.
> 
> As far as I can see what you're trying to achieve is already possible by passing muliple sort parameters, i.e. `sort=foo,bar,asc&sort=fooBar,desc` already results in `foo asc, bar asc, fooBar, desc`.

I've created a issues to discuss it.
[DATACMNS-1454](https://jira.spring.io/projects/DATACMNS/issues/DATACMNS-1454)

**Comment by odrotbohm** [comment]
Lovely, thanks! Let's move over there for general discussion now.

**Comment by andyslin** [comment]
OK, thank you very much!

**Comment by mp911de** [comment]
We discussed this issue with our team and came to the conclusion that we do not want to change the format nor introduce an alternative one. You can customize the format by providing your own `SortHandlerMethodArgumentResolver` bean.

**Pull request closed without merging**
