### PR TITLE
DATACMNS-1071

### PR DESCRIPTION
**Pull request by cwiejack**
DATACMNS-1073 - Obvious Fix remove unnecessary generic

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cwiejack Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=220)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=220) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by wendigo** [comment]
Same as https://jira.spring.io/browse/DATACMNS-1071 ;-) (I was first :P)

**Comment by cwiejack** [comment]
Damn ;)
Should I close the bug and the PR?

**Comment by schauder** [comment]
I just closed the issue as duplicate but assigned this PR to DATACMNS-1071 since there was no PR for it yet.

**Comment by olivergierke** [comment]
That's merged.

**Pull request closed without merging**
