### PR TITLE
DATACMNS-1067 - Fix not to call @AfterDomainEventPublication method from Collection of entities.

### PR DESCRIPTION
**Pull request by sis-yoshiday**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACMNS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

I've fixed below ticket, please review.
https://jira.spring.io/browse/DATACMNS-1067

### CODE REVIEW

**Comment by olivergierke** [comment]
One thing I am kind of puzzled about is the mismatch between the fix and the description in the original ticket. The ticket claims a problem with `save(Iterable)` being called. The fix however deals with the events that are potentially to be emitted. Can you clarify?

**Comment by olivergierke** [comment]
I think I got it.  The essential fix referring to the ticket is that the object that the clearing method is invoked on is the aggregate root, not the parameter object. However, I am now unsure about the change to only clear the events if they have been exposed. This is a feature we can discuss, but it's not something I would want to couple with the fix for the issue described in the ticket.

**Comment by sis-yoshiday** [comment]
Yes, we should call clearingMethod even if events is empty.
Tomorrow, I fix it.

**Comment by olivergierke** [comment]
Thanks for clarifying. Already at it :).

**Pull request closed without merging**
