### PR TITLE
DATACMNS-531 - Add support for a simplified syntax in request paramet…

### PR DESCRIPTION
**Pull request by sancho21**
Added new SimpleSortHandlerMethodArgumentResolver as an alternative to SortHandlerMethodArgumentResolver implementation.

This is for simplified sort parameter with sign. I have feeling that SortDefaultUnitTests.java should be independent of the SortHandlerMethodArgumentResolver implementation.

### CODE REVIEW

**Comment by olivergierke** [comment]
So what is the plan on integrating this? We can't just simply replace the current one as that would break existing applications.

Regarding the split of the unit tests for `SortDefault` — You now tied those tests to your implementation, which doesn't necessarily change the situation.

To be completely hones, I am not even sure I want to "solve" the issue, as we're basically just trading one way with the other and I am pretty sure, if we moved to the new format people that preferred the old format.

**Comment by sancho21** [comment]
On https://jira.spring.io/browse/DATACMNS-531, you said that you want clear separation. So, I made a separate class for simple sort option. This way, users still can either choose the existing SortHandlerMethodArgumentResolver or the new SimpleSortHandlerMethodArgumentResolver as both classes are there for them to choose. 

Or, is it better to just add another flag to the existing class like?

**Comment by jeffsegal** [comment]
+1 on this PR. It snaps nicely in and satisfies a very common pattern in APIs (+/- sort direction).

**Comment by pivotal-issuemaster** [comment]
@sancho21 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=166) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by mp911de** [comment]
Thanks for your PR. Closing this one as per comment in the linked ticket as we do not intend to add additional/alternative sort formats. You can customize the format by providing your own `SortHandlerMethodArgumentResolver` bean.

**Pull request closed without merging**
