### PR TITLE
DATACMNS-739 - Performance improvement for MultiTransactionStatus

### PR DESCRIPTION
**Pull request by ameyjadiye**
Its always better in Multi-threading and low latency application that not to have single lock on Map.
ConcurrentHashMap holds default 16 locks which significantly improves the performance than having single lock SyncronizedMap.

### CODE REVIEW

**Comment by olivergierke** [comment]
Do you have any before / after comparisons? `MultiTransactionStatus` hasn't showed up in profilings so far.

@jexp - Opinions?

**Comment by jexp** [comment]
I think a perf test would make sense. 

You only benefit from the 16 segments if you have that high concurrency level.

**Comment by ameyjadiye** [comment]
ok, let me put the perf results here .. also let me make it configurable so programmers can opt for number of locks, if configured as 1 its nothing but the simple  _HashMap_, and default should be _concurrencyLevel(1)_ , if some one using it in multi-threading environment programmers can increase it.

**Comment by olivergierke** [comment]
Is there any further feedback? If not I'd stick to the current implementation and close this one without merge.

**Comment by ameyjadiye** [comment]
Hi @olivergierke , I totally forgot to work on this and this was sitting in my **todo** from long , let me pull some comparison stats and junits if possible - thanks for not closing this.

**Comment by mp911de** [comment]
Closing this issue after a significant period of inactivity.

**Pull request closed without merging**
