### PR TITLE
Improve error message if store module doesn't support a well-known fragment interface

### LINKED ISSUE #2341: Improve error messages if a repository cannot be created
**[Tera](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49634)** opened **[DATACMNS-1812](https://jira.spring.io/browse/DATACMNS-1812?redirect=false)** and commented

I'm trying to use Spring data JDBC with Query DSL in Kotlin. This is my repository

 

```java
@Repository
interface AgentRepository : PagingAndSortingRepository<Agent, Int>, QuerydslPredicateExecutor<Agent> {}
```

I've integrated these dependencies in my Gradle build:

```java
implementation 'org.springframework.boot:spring-boot-starter-data-jdbc:2.3.3'
implementation("com.querydsl:querydsl-core:4.4.0") 
kapt "com.querydsl:querydsl-apt:4.4.0:jpa"
```

As soon as I try to start my application I get this error:

```java
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentRepository' defined in it.dove.braniac.repositories.AgentRepository defined in @EnableJdbcRepositories declared on BraniacApplication: Invocation of init method failed; nested exception is org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract long org.springframework.data.querydsl.QuerydslPredicateExecutor.count(com.querydsl.core.types.Predicate)! Reason: No property count found for type Agent!
```

I can't understand what I'm doing wrong and if there is an incompatibility between Spring Data JDBC and QueryDSL

 

The same issue happens if I try to change from PagingAndSortingRepository to simple CrudRepository

---

**Affects:** 2.3.4 (Neumann SR4)

### PR DESCRIPTION
**Pull request by mp911de**
We now throw a `RepositoryCreationException` (or subclass) when a repository cannot be created due to a missing fragment, a fragment without implementation or if a well-known fragment is not supported by the repository factory.

Closes #2341

### CODE REVIEW

**Comment by odrotbohm** [comment]
What's the exact difference between `FragmentNotImplementedException` and `MissingFragmentException`? Superficially they sound very similar and I don't quite get the difference from the Javadoc

**Comment by mp911de** [comment]
`MissingFragmentException` is used when we identify custom methods and do not find an implementation for the method to be called. `MFE` isn't tied to a particular fragment, it's expressing that the composition doesn't contain what we're looking for. `FragmentNotImplementedException` signals that we identified a fragment but it has no implementation attached. `FragmentNotImplementedException` can only happen when configuring `RepositoryComposition` manually and it should not occur when bootstrapping repositories using repository scanning.

**Comment by odrotbohm** [comment]
Does `IncompleteFragmentException` describe the situation better than `MissingFragmentException` then? A fragment is the entire interface, right, not just an individual method within it?

**Comment by mp911de** [comment]
A fragment is an entire interface. I think `IncompleteRepositoryCompositionException` puts it better because we're in the context of a `RepositoryComposition` and we can't tell in that case which fragment is affected.

**Comment by odrotbohm** [comment]
Any reason for the move to `RepositoryException` and drop the `Creation`? That sounds rather generic. Isn't all that structural validation tied to the repository creation?

**Comment by mp911de** [comment]
Most exceptions happen indeed during repository creation. Some can happen when calling a repository method for a composition that wasn't configured properly. I'm not sure we can catch all failures early on. If we roll back runtime (invocation checks) for missing fragments/fragment implementations during repository method invocation, we could retain the concept of a creation exception.

**Comment by odrotbohm** [comment]
How about `RepositorySetupException`? That slightly nudges into the direction of the arrangement of the repository.

**Comment by mp911de** [comment]
That's merged now.

**Pull request closed without merging**
