### PR TITLE
chore: add Smallrye Mutiny support

### PR DESCRIPTION
**Pull request by hantsy**
aligned to Spring 5.3.10 which added SmallRye Mutiny support, see: https://github.com/spring-projects/spring-framework/pull/27331

### CODE REVIEW

**Comment by hantsy** [comment]
depends on https://github.com/spring-projects/spring-data-build/pull/1545

**Comment by mp911de** [comment]
Thanks a lot for your contribution. For the time being we would like to include only the addition of Mutiny to our registry and adapter infrastructure. Care to remove the repository base interfaces as these aren't required and we do not have native implementations using Mutiny?

**Comment by hantsy** [comment]
Is there any Repository implementations using RxJava 2/3?  

I would like to add it firstly, and then add a standalone spring data hibernate module(active and blocking). Currently Spring Data JPA does not support reactive APIs, but HibernateReacitve provides **JPA like** APIs to reactive world),  Hibernate Reactive has built-in SmallRye Mutiny support.

For those RDBMS developers who are familiar with JPA, migrating to Hibernate Reactive is more reasonable than using R2dbc(not mature as Jdbc till now).

**Comment by mp911de** [comment]
>  would like to add it firstly, and then add a standalone spring data hibernate module(active and blocking). 

For the time being, it can be a local interface in a Spring Data Hibernate Reactive module.

> Is there any Repository implementations using RxJava 2/3?

Kind of. With Spring Data 2.x we support RxJava 1 while there is no base RxJava 1 base repository. Generally, Spring Data creates adapters around reactive types so one can use e.g. MongoDB through RxJava 2/3. In the early days, Couchbase was built on RxJava 1 but the repository could be used through `ReactiveCrudRepository`.

**Comment by hantsy** [comment]
I see, the ReactiveAdapter can convert between them,  for Spring projects, Reactor is enough.

**Comment by hantsy** [comment]
@mp911de  Updated and rebased on main.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
