### PR TITLE
DATACMNS-953 - Fix method ExampleMatcher.GenericPropertyMatchers.exact()

### PR DESCRIPTION
**Pull request by Rib47**
DATACMNS-953 - Fixed exact() method from ExampleMatcher.GenericPropertyMatchers class.
Tests added also.

### CODE REVIEW

**Comment by olivergierke** [comment]
The referenced ticket has just be marked resolved: https://jira.spring.io/browse/DATACMNS-953

**Comment by Rib47** [comment]
Why you had not merge this pull?

**Comment by olivergierke** [comment]
Because it was submitted when the other commit already had been pushed.

**Comment by Rib47** [comment]
Ok.
We had issue with this error when use ExampleMatchers in our project.

**Pull request closed without merging**
