### PR TITLE
Add @JpaRepositoryCombination function. avoid duplicate inheritance i…

### PR DESCRIPTION
**Pull request by caomingjie-code**
…nterface

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@caomingjie-code Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2311)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2311) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@caomingjie-code Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=2311)!

**Comment by caomingjie-code** [comment]
When I use spring framework, I found that if I need A extend interface E, F, G , H and several other interfaces, while I alse need B extends A(I can also make B extends E, F, G, H and several other interfaces, but it's redunctant). But it will throw some errors. In a word, as for now the framework could not  implement hierarchy extension.

**Comment by schauder** [comment]
At the very least this needs some tests and "JPA" should not part of the name, since it would apply to all stores.

**Comment by caomingjie-code** [comment]
I don't think you understand what I mean, I kwon that the jpa would apply to all stores,  and I' ll submit the test cases and the details.

**Comment by schauder** [comment]
> I don't think you understand what I mean, 
That is of course perfectly possible. Please explain it to me.

> I kwon that the jpa would apply to all stores, and I' ll submit the test cases and the details.
Good, thanks.

**Comment by caomingjie-code** [comment]
Now I'm going to talk about the problems I' ve encountered in doing architecture in a project:
The purpose of my design is to integrate mybatis and jpa. So I defined two interfaces, one is a Jpa-based interface, named BaseJpa (BaseJpa Jpa Repository), and the other is to use the' Customizing Individual Repositories' function to implement the BaseBatis (mainly encapsulate the function) interface
So my friends can use jpa or mybatis, can use them together. Over time, I found a large number of repetitive inheritance (duplicate inheritance BaseJpa,BaseBatis) in the project, so I made an adjustment and created a new interface class BaseJpaBatis. I did this
(public interface BaseJpaBatis<T,) Annex ID>extends BaseJPA<T, ID>, BaseBatis<T, ID>), BaseJpaBatis, inherited from the interface BaseJPA. and repeat the inherited code (BookService extends BaseJpa<Book,); and Integer>, BaseBatis<Book, Integer>{...}
Rewrite to BookService extends BaseJpaBatis<Book,Integer>{...}) to inherit only BaseJpaBatis. The project startup error was found after modification (this is the error log at the time the project started: Caused by：org.springframework.data. mapping.PropertyReferenceException：No property insertSqlByPojo found for type BrowserUserEntry), after careful reading of the source code found that jpa did not find the BaseBatis interface, the source code is only found BaseJpaBatis and did not continue to look up. So I designed an annotation @ JpaRepositoryCombination to indicate that the current BaseJpaBatis interface is a composite interface that should be fetched
Directly inherited parent interface (excluding ancestral interface) to replace the current interface. And I modified the jpa source code, currently only used internally (and used for a period of time), after a period of use found that the interface in the project repeated inheritance problem has been improved, and now the project has been running steadily without any problems, so I want to submit my ideas and code to the github to help more people.

**Comment by caomingjie-code** [comment]
Now I'm going to talk about the problems I' ve encountered in doing architecture in a project:
The purpose of my design is to integrate mybatis and jpa. So I defined two interfaces, one is a Jpa-based interface, named BaseJpa (extends JpaRepository), and the other is to use the' Customizing Individual Repositories' function to implement the BaseBatis (mainly encapsulate the function) interface
So my friends can use jpa or mybatis, can use them together. Over time, I found a large number of repetitive inheritance (duplicate inheritance BaseJpa,BaseBatis) in the project, so I made an adjustment and created a new interface class BaseJpaBatis（public interface BaseJpaBatis<T, ID> extends BaseJPA<T,ID>,BaseBatis<T,ID>）. The BaseJpaBatis interface inherits BaseJpaBatis,BaseJPA.  and repeat the inherited code (BookService extends BaseJpa<Book,Integer>,BaseBatis<Book,Integer>{...}
Rewrite to BookService extends BaseJpaBatis<Book,Integer>{...}) to inherit only BaseJpaBatis. The project startup error was found after modification (this is the error log at the time the project started: Caused by：org.springframework.data. mapping.PropertyReferenceException：No property insertSqlByPojo found for type Book), after careful reading of the source code found that jpa did not find the BaseBatis interface, the source code is only found BaseJpaBatis and did not continue to look up. So I designed an annotation @ JpaRepositoryCombination to indicate that the current BaseJpaBatis interface is a composite interface that should be fetched
Directly inherited parent interface (excluding ancestral interface) to replace the current interface. And I modified the jpa source code, currently only used internally (and used for a period of time), after a period of use found that the interface in the project repeated inheritance problem has been improved, and now the project has been running steadily without any problems, so I want to submit my ideas and code to the github to help more people.

**Comment by caomingjie-code** [comment]
thanks and I hope you understand my idea

**Comment by caomingjie-code** [comment]
Now I'm going to talk about the problems I' ve encountered in doing architecture in a project:
The purpose of my design is to integrate mybatis and jpa. So I defined two interfaces, one is a Jpa-based interface, named BaseJpa (extends JpaRepository), and the other is to use the' Customizing Individual Repositories' function to implement the BaseBatis (mainly encapsulate the function) interface
So my friends can use jpa or mybatis, can use them together. Over time, I found a large number of repetitive inheritance (duplicate inheritance BaseJpa,BaseBatis) in the project, so I made an adjustment and created a new interface class BaseJpaBatis（public interface BaseJpaBatis<T, ID> extends BaseJPA<T,ID>,BaseBatis<T,ID>）. The BaseJpaBatis interface inherits BaseJpaBatis,BaseJPA.  and repeat the inherited code (BookService extends BaseJpa<Book,Integer>,BaseBatis<Book,Integer>{...}
Rewrite to BookService extends BaseJpaBatis<Book,Integer>{...}) to inherit only BaseJpaBatis. The project startup error was found after modification (this is the error log at the time the project started: Caused by：org.springframework.data. mapping.PropertyReferenceException：No property insertSqlByPojo found for type Book), after careful reading of the source code found that jpa did not find the BaseBatis interface, the source code is only found BaseJpaBatis and did not continue to look up. So I designed an annotation @ JpaRepositoryCombination to indicate that the current BaseJpaBatis interface is a composite interface that should be fetched
Directly inherited parent interface (excluding ancestral interface) to replace the current interface. And I modified the jpa source code, currently only used internally (and used for a period of time), after a period of use found that the interface in the project repeated inheritance problem has been improved, and now the project has been running steadily without any problems, so I want to submit my ideas and code to the github to help more people.

**Comment by mp911de** [comment]
In that case, you're better off by providing a custom `JpaRepositoryFactoryBean` respective `JpaRepositoryFactory` that includes the MyBatis fragment if the repository interface declares MyBatis functionality. 

There's similar functionality in Spring Data JPA that conditionally enables Querydsl when a repository extends `QuerydslPredicateExecutor`. Take a look at:

https://github.com/spring-projects/spring-data-jpa/blob/eb023fc77af530b22ec6a0e158fad3cb3cd13e62/src/main/java/org/springframework/data/jpa/repository/support/JpaRepositoryFactory.java#L237-L260

Using customization in `JpaRepositoryFactory` makes much more sense than sub-interface fragment discovery.

**Comment by caomingjie-code** [comment]
My problem is the repeated inheritance of jpa interfaces and custom warehouse interfaces, not mybatis integration. If the custom warehouse interface and Jpa interface still have the problem of repeated inheritance, I think the custom warehouse design is very difficult

**Comment by caomingjie-code** [comment]
I think this is a custom warehouse interface optimization problem

**Pull request closed without merging**
