### PR TITLE
DATACMNS-1672 - Doc fix - methods require brackets

### PR DESCRIPTION
**Pull request by GingerGeek**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@GingerGeek Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=335)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=335) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
That's an obvious fix. No need to sign the CLA.

**Comment by pivotal-issuemaster** [comment]
@GingerGeek This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and backported now.

**Pull request closed without merging**
