### PR TITLE
Expose BeanFactory to RepositoryFactorySupport implementations. 

### PR DESCRIPTION
**Pull request by gregturn**
This is needed to close https://github.com/spring-projects/spring-data-jpa/pull/2513.

### CODE REVIEW

**Comment by mp911de** [comment]
Let's keep that change local to the JPA module. Since `RepositoryFactorySupport` implements `BeanFactoryAware` already, it would make sense to override the `setBeanFactory` method in the JPA Repository Factory.

**Comment by gregturn** [comment]
I don’t follow. This is adding getBeanFactory, not setBeanFactory.

**Comment by mp911de** [comment]
What I mean is, that the method that is used to set the bean factory can be overridden in the JPA repository factory to capture the actual value (`BeanFactory` instance).

**Comment by gregturn** [comment]
Withdrawn.

**Pull request closed without merging**
