### PR TITLE
DATACMNS-1827 - Pageable and Sort arguments with empty qualifier value shouldn't be prefixed with delimiter.

### PR DESCRIPTION
**Pull request by vpavic**
This resolves [DATACMNS-1827](https://jira.spring.io/browse/DATACMNS-1827).

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACMNS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Comment by vpavic** [comment]
@mp911de, I just noticed that you polish commit considered `MergedAnnotations` only for `PageableHandlerMethodArgumentResolverSupport` but not `SortHandlerMethodArgumentResolverSupport` - was that intentional?

**Comment by mp911de** [comment]
Meh, I missed `SortHandlerMethodArgumentResolverSupportˋ. Do you want to submit a PR formten remaining one or should I take care of it?

**Comment by vpavic** [comment]
I can handle it later in the day, I assume it's not that urgent as `2.4.1` seems to have went out few hours ago?
Also, having in mind that'll be targeted at `2.4.2`, we need a new JIRA issue as well, right?

**Comment by mp911de** [comment]
We can reuse the same issue and add 2.4.2 as fix version.

**Pull request closed without merging**
