### PR TITLE
DATACMNS-1673 - Use Method.getParameterCount() where possible to improve performance

### PR DESCRIPTION
**Pull request by stsypanov**
Subj

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for your contribution. Typically, we expect a Jira ticket first along with an expressive commit and pull request title. Check out our [contribution guide](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc). Care to look at least into a better commit and pull request title?

The code changes make sense from an optimization perspective.

**Comment by stsypanov** [comment]
Hello, I could rename this to 'Use Class.getParameterCount() where possible for performance improvement'

**Comment by mp911de** [comment]
Yeah, it's still better than `tiny code improvements` and `experimental`. Feel free to amend/rebase your changes and force-push these. GitHub will adapt the changes accordingly.

**Comment by stsypanov** [comment]
I've changed the title and commit message, but cannot rename the branch. Is it required?

**Comment by mp911de** [comment]
Thanks a lot. The branch name doesn't really matter. I'll have a look in the coming days.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged, polished, and backported now.

**Pull request closed without merging**
