### PR TITLE
Detect nullable marker parameters in constructor arguments. 

### PR DESCRIPTION
**Pull request by christophstrobl**
This **draft** seeks to introduce a `nullableMarker` flag to the `Parameter` abstraction. If set, it is safe skip and `null` the parameter value right away.

The `PreferredConstructorDiscoverer` for Kotlin will use this flag when detecting a `DefaultConstructorMarker` argument within the java constructor which is there (as the name indicates) to solely mark the constructor to use but does not map to any parameter from the source Kotlin type, resulting in an unresolvable parameter name/target property for the parameter.
This change will allow the `ClassGeneratingEntityInstantiator` to operate types using Kotlin inline classes.

I think it would also make sense to discuss if the usage of the newly introduced method makes sense in the `ParameterValueProvider` implementations like `PersistentEntityParameterValueProvider` to shortcut the value lookup by simply returning `null`

Closes: #1947

### CODE REVIEW

**Comment by mp911de** [comment]
We have a few other flavors of non-domain arguments for constructors such as the outer class instance (for non-static inner classes) or nullable mask markers.

In all other places, we do not create a `Parameter` in the first place and I think we should follow the same pattern here as well.

**Comment by christophstrobl** [comment]
So we'd end up with a signature that requires us to hand more arguments than we have parameters for, which is odd in first place.

**Comment by mp911de** [comment]
The alternative to introducing all sorts of markers isn't a better variant. Kotlin nullability integer masks are spread over a few constructor integer parameters. For every 32 nullable parameters there's one additional integer bit mask.

**Comment by christophstrobl** [comment]
have an example for that? I doubt it's targeting the same scenario.

**Comment by christophstrobl** [comment]
since we do not have a stable API contract (see: [1947](https://github.com/spring-projects/spring-data-commons/issues/1947#issuecomment-1413947156)) other than the public constructor, and cannot safely invoke the method  with one parameter in the model missing skipping parameters seems to be a bad choice. 
Maybe there's a difference in the use case you mention above that would allow to ignore entire constructors, but not the parameter if we detect it.

**Pull request closed without merging**
