### PR TITLE
DATACMNS-1736 - Use BeanFactory lookup in configuration classes instead of intercepted local bean methods

### PR DESCRIPTION
**Pull request by mp911de**
We now use `@Configuration(proxyBeanMethods = false)` and use `BeanFactory` bean lookups to avoid CGlib proxy creation.

Using Spring's `BeanProvider.getIfUnique(…)` instead of catching `NoSuchBeanDefinitionException`.

---

Related ticket: DATACMNS-1736

### CODE REVIEW

**Comment by wwadge** [comment]
Small aside: this PR is also needed for GraalVM to function without a lot of hacks

**Comment by mp911de** [comment]
That's exactly why we're exploring this option. Likely, we will go ahead and introduce method-injection instead of lookup methods for the next version and discard this PR.

**Comment by gregturn** [comment]
@odrotbohm @mp911de 

I pushed another commit that pivots away from protected methods and instead, when needed, has a protected `Lazy` that can be overridden in subclasses.

wdyt?

**Comment by gregturn** [comment]
I'd love to polish this up and merge to master branch. Then I can consume these changes in Spring Data REST.

**Pull request closed without merging**
