### PR TITLE
DATACMNS-1331 - Add ZonedDateTimeToDateConverter

### PR DESCRIPTION
**Pull request by postalservice14**
Add a converter for ZonedDateTime to Date.

### CODE REVIEW

**Comment by konstantin-krasheninnikov-ullink** [comment]
It would be nice to merge this. It is a very small, but very useful change. 

It seems those who use ZoneDateTime for @CreatedDate and @LastModifiedDate can't upgrade to Spring Boot 2 without falling back to Date. There seems to be no way to add a custom converter to HttpHeadersPreparer's conversionService.

Thank you.

**Comment by hopperd** [comment]
What is holding this one up, seems pretty straight forward?

**Comment by konstantin-krasheninnikov-ullink** [comment]
The issue ([DATACMNS-1331](https://jira.spring.io/browse/DATACMNS-1331)) was raised almost a year ago. Please make this happen. Thanks.

**Comment by mp911de** [comment]
Closing without merge as per comment in [DATAREST-1355](https://jira.spring.io/browse/DATAREST-1355).

**Pull request closed without merging**
