### PR TITLE
ChainedTransactionManager integration tests

### PR DESCRIPTION
**Pull request by mit-jones**
There looks to be an issue with the ChainedTransactionManager.

Two integration tests (ChainedTransactionManagerIntegrationTests) have been added both functionally the same, both should pass. However one fails (with a CannotCreateTransactionException) where it calls a method that has been advised with transaction propagation NOT_SUPPORTED.

I think there is an issue with the ChainedTransactionManager possibly in the getTransaction() method where the synchronizationManager is initialised regardless of the transaction propagation. Compare this with AbstractPlatformTransactionManager.getTransaction() where initSynchronization() would only be called for transaction propagation of REQUIRED, REQUIRES_NEW and NESTED.

This issue is probably related to https://jira.spring.io/browse/DATACMNS-370 so will be added to this existing JIRA

### CODE REVIEW

**Comment by olivergierke** [comment]
I don't think we can merge this as we're not gonna introduce dependencies to JDBC related artifacts in Spring Data Commons. Still would like to get @jexp's opinion on that one.

**Comment by mit-jones** [comment]
Okay understood but how do we proceed from here, I believe the issue still remains. I do not know another way of providing a reproducible test case that can highlight this issue. If you can give me some guidance I am okay with trying another approach but I think it will be difficult to prove without an integration test.

**Comment by pivotal-issuemaster** [comment]
@mit-jones Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=148) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by schauder** [comment]
As @olivergierke explained above we won't merge this one. This does not affect the underlying issue.

**Pull request closed without merging**
