### PR TITLE
DATACMNS-1245 - Consider Kotlin metadata annotation for Kotlin class kind retrieval

### PR DESCRIPTION
**Pull request by mp911de**
We now inspect Kotlin's `Metadata` annotation to determine the kind of a Kotlin class.

Previously we used Kotlins internal API to introspect classes. Because this API is not public and can be changed at any time we rely on Kotlins annotations as they are supposed to not change in near future.

---

Related ticket: [DATACMNS-1245](https://jira.spring.io/browse/DATACMNS-1245).

### CODE REVIEW

**Comment by mp911de** [comment]
The code is called a few times during initializations of `EntityInstantiator`, `MethodInvocationValidator`, `PreferredConstructorDiscoverer` and `AbstractMappingContext.shouldCreatePersistentEntityFor`. 

I omitted `static final` caches in the first place to avoid references preventing `ClassLoader` cleanup but maybe it's worth to encapsulate the code in an own class held in a `WeakReference`.

**Comment by olivergierke** [comment]
It looks like we have a early return in place we realize it's not a Kotlin class in the first place so we should be fine, I think. We can approach this in case it comes up in benchmarks lazily.

**Comment by olivergierke** [comment]
Upon closer inspection, even the early return requires repeated reflection lookups in `loadKotlinClass(…)`. I wonder if the general reflection lookup couldn't just keep what ends up in `create` and `typeFactory` in static fields for subsequent reuse?

**Comment by mp911de** [comment]
Putting these values into static fields creates references that possibly prevent finalizing, therefore I'd rather go for `WeakReference` fields.

**Comment by mp911de** [comment]
Changed the approach after receiving feedback from Jetbrains. Evaluating `@Metadata(k=…)` is the more stable approach.

**Comment by olivergierke** [comment]
Wow, that looks dramatically simpler :)

**Pull request closed without merging**
