### PR TITLE
DATACMNS-1512 - Allow customization of ConversionService in RepositoryFactorySupport

### PR DESCRIPTION
**Pull request by wreulicke**
Fix [DATACMNS-1512](https://jira.spring.io/projects/DATACMNS/issues/DATACMNS-1512)

I have a library using spring-data-commons, [spring-data-mirage](https://github.com/dai0304/spring-data-mirage).

In the library, it is able to use custom collection as return type, such as a below custom collection.

We have the interface, Chunk and the implementation, ChunkImpl.
But, We cannot return ChunkImpl as implementation of Chunk in 2.1.6.RELEASE of spring-data-commons.
This causes by element type conversion introduced by https://jira.spring.io/browse/DATACMNS-1482.

```
public interface Chunk<T> extends Collection<T> {
  // some methods...
}

public class ChunkImpl<T> implements Chunk<T> {
  // some implmentations...
}
```

I cannot find the workaround.
So, I would like to make to register custom conversion.

# checklist

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACMNS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by mp911de** [comment]
It would make sense to have an externally configurable `ConversionService` by introducing a setter instead of delegating converter registration calls.

Beyond that, we could pre-initialize `ConfigurationService` with a shared and pre-configured instance. `QueryExecutionResultHandler` uses `ConfigurationService` without modifying it and we would not create a `ConfigurationService` per repository instance. Probably a separate ticket though.

Wdyt @odrotbohm?

**Comment by wreulicke** [comment]
@mp911de Thanks for your review. 😄 

I implemented to use pre-configured instance in 9c90f83. 
What do you think?

**Comment by wreulicke** [comment]
rebased

**Comment by odrotbohm** [comment]
Please refer to the comments and questions made on the ticket back in May. I don't think we should or can move ahead with this one without the concerns addressed.

**Pull request closed without merging**
