### PR TITLE
DATACMNS-1580 - Updated documentation

### PR DESCRIPTION
**Pull request by hijxf**
Initially, I went to the API to try and see if the method returned a potentially modified `entity`, but I felt the documentation wasn't clear on that. So we went to test it and _obviously_ was the case 😅.

After studying this doc for more than a couple minutes, we can assume it returns a potential modified `entity` based on its return type, but still felt like we needed to update the doc 🤓.

Just my opinion, but hopefully this helps. I also don't feel like I deserve a spot in the authors page, so I didn't add my name even though it's part of the checklist...

Thanks!
Jef

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACMNS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hijxf Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=401)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=401) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hijxf Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-commons&pullRequestId=401)!

**Comment by odrotbohm** [comment]
I am puzzled because the Javadoc literally said:

> the save operation might have changed the entity instance completely

We have to be careful about changes here as we have to make sure that de documented behavior matches what the different store implementations actually do. The extended generics are only in place so that you can get a potential sub-type you hand into the method as the subtype itself. I.e. the generics declaration does not have anything to do with the fact, that the method might just return the same instance but it could also return a completely new one, e.g. when dealing with immutable aggregate types.

That said, I'm not convinced the new wording is better than the old, as – in fact – it suggests modification where potentially none happens.

**Comment by hijxf** [comment]
That's a great point. I think the verbage in the description is fair and
clear in the original code. Would you agree adding a semi colon after 'the
saved entity' would be clearer? It's a small enough change as just looking
at the return type can be confusing. I also want to be clear I'm not trying
to split hair here, but just suggest.

Thanks!

**Comment by hijxf** [comment]
Updated the PR with my suggested change. If you don't feel that it's necessary, no problem. Thanks for your time.

**Comment by mp911de** [comment]
That's merged and backported now. Thank you.

**Comment by hijxf** [comment]
Thanks!

**Pull request closed without merging**
