### PR TITLE
DATACMNS-676 - Investigate support for RxJava in Repositories.

### PR DESCRIPTION
**Pull request by thomasdarimont**
Add support for RxJava Observables as as supported return type in Repository finder methods.
Added optional RxJava dependency.

### CODE REVIEW

**Comment by jmnarloch** [comment]
@thomasdarimont @olivergierke Is there a chance that this pull request will ever get merged?

**Comment by geoand** [comment]
This looks like a very interesting feature!

It would be great to know your thinking regarding whether or not it will be released.

Thanks

**Comment by olivergierke** [comment]
It eventually will but most likely in the course of a much bigger set of changes to adhere to the Spring 5 features in the reactive area.

**Comment by geoand** [comment]
Thanks very much for the update @olivergierke!

**Comment by mp911de** [comment]
Closing this PR because reactive support is continued with https://jira.spring.io/browse/DATACMNS-836. We will provide native reactive support using reactive drivers. A conversion of scalar values or futures into reactive wrapper types is not intended.

**Pull request closed without merging**
